import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/NavBar";
import GoodleAnalyticsScript from "@/components/GoodleAnalyticsScript";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500"],
});
const mtchaEaLge = localFont({
  src: "../assets/fonts/Matcha-EaLge.woff2",
  variable: "--font-mtcha-ealge",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "...",
    description: "...",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="winter">
      <GoodleAnalyticsScript />
      {/* mtchaEaLge.className */}
      <body className={mtchaEaLge.variable}>
        <NavBar />
        <main className="p-5">{children}</main>
      </body>
    </html>
  );
}
